src/modules/unit/components/SingleUnitModalContainer.js
Adds observation time for temperatures.
=> KUVA-152: Add updated time to temperature observations

.gitlab-ci.yml, README.md, package.json, src/modules/common/components/App.js, src/modules/common/helpers.js, src/modules/map/components/UserLocationMarker.js, src/modules/search/components/SearchBar.js, src/modules/search/components/SearchContainer.js, src/modules/search/components/SearchSuggestions.js, src/modules/search/components/UnitSuggestion.js, src/modules/unit/__tests__/UnitFilterLabel.test.js, src/modules/unit/__tests__/__snapshots__/UnitFilterLabel.test.js.snap, src/modules/unit/__tests__/seasons.test.js, src/modules/unit/components/FeedbackModal.js, src/modules/unit/components/ListView.js, src/modules/unit/components/SingleUnitModalContainer.js, src/modules/unit/components/SingleUnitOnMap.js, src/modules/unit/components/SortSelectorDropdown.js, src/modules/unit/components/UnitBrowser.js, src/modules/unit/components/UnitFilterLabel.js, src/modules/unit/components/UnitGeometry.js, src/modules/unit/components/UnitsOnMap.js, src/modules/unit/seasons.js, src/setupTests.js, yarn.lock
- Updated dependencies when necessary
- Auto eslinted the project so that pre-push hook will pass
- Git pre-push hook no longer runs automated tests in favor of CI pipeline
=> Automated tests capability

locales/en.json, locales/fi.json, locales/sv.json, package.json, src/jest.setup.js, src/modules/common/components/translation/TranslationProvider.js, src/modules/common/components/translation/__tests__/TranslationProvider.test.js, src/modules/common/enzymeHelpers.js, src/modules/home/components/Time.js, src/modules/home/components/TimeAgo.js, src/modules/unit/components/ObservationStatus.js, src/modules/unit/components/SingleUnitModalContainer.js, src/modules/unit/components/UnitFilterLabel.js, src/modules/unit/components/__tests__/SingleUnitModalBody.test.js
- Synchronizes moment locale to current language in order to use "from"
times from moment directly
- Removes require.context, because jest does not support it
=> ULK-80 | Render live location temperature

.github/PULL_REQUEST_TEMPLATE.md
Adds a pull request template which supports developers in making more consistent PR descriptions.
=> Chore | Add pull request template

README.md
The main point of this PR is to report an issue, which I can't do because they've been disabled from this repo.
The HTTPS certificate is invalid for this site, which means the site is unusable:
https://www.ulkoliikunta.fi/
=> End paragraph with fullstop / Reporting invalid HTTPS certificate

CHANGELOG.md, locales/en.json, locales/fi.json, locales/sv.json, src/modules/unit/components/UnitBrowser.js, src/modules/unit/components/_unit-browser.scss
Adds missing accessible names to map buttons.
[ULK-94](https://helsinkisolutionoffice.atlassian.net/browse/ULK-94)
This has been tested manually with a screen reader.
As a screen reader user
1. Tab to map and list buttons
2. Expect them to have accessible names
3. Expect accessible names to make sense to you
=> ULK-94 | Add accessible names to result toggle buttons

CHANGELOG.md, src/modules/search/components/SearchBar.js
Adds missing search landmark.
[ULK-105](https://helsinkisolutionoffice.atlassian.net/browse/ULK-105)
=> ULK-105 | Add missing aria-landmarks

CHANGELOG.md, package.json
Merge release 1.1.5 documentation back into develop.
=> [Develop] Release 1.1.5

CHANGELOG.md, package.json
Merge release documentation back into develop.
=> [develop] Release 1.1.6

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enchancement.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Because this project is not actively maintained, provide more complete
instructions for creating issues in order to help reporters provide the
relevant information for resolving their concerns.
=> Chore | Add issue templates

CHANGELOG.md, package.json, public/index.html, src/locales/en.json, src/locales/fi.json, src/locales/sv.json, src/modules/common/components/App.js, src/modules/common/components/Page.js, src/modules/common/components/__tests__/Page.test.js, src/modules/common/pathUtils.js, src/modules/home/components/HomeContainer.js, src/modules/meta/AppMeta.js, src/modules/meta/LanguageMeta.js, src/modules/meta/PageMeta.js, src/modules/meta/helpers.js, src/modules/unit/helpers.js, yarn.lock
Adds and changes meta information for the application.
Adds some common missing meta fields and adjusts the current titles and descriptions for pages.
[ULK-129](https://helsinkisolutionoffice.atlassian.net/browse/ULK-129)
=> ULK-129 | Update and expand meta information

.dockerignore, .github/workflows/production.yml, .gitignore, CHANGELOG.md, Dockerfile, package.json, public/robots.txt, scripts/generate-sitemap.ts, scripts/tsconfig.json, yarn.lock
Adds a script that generates a sitemap for the site.
The sitemap is generated based on static configurations and the output of the unit API.
A request is made to the unit API to find the units that are relevant to this service. That result list is then used to generate all the possible unit addresses for ulkoliikunta.fi.
At the moment about 300 pages are indexed from Ulkoliikunta.fi. There are about 600 units, so this map should help Google find about 300 pages it has not found previously.
The sitemap building can be configured by using the `GENERATE_SITEMAP` environment variable. The application has been configured to build the sitemap in conjunction with builds in the production environment (NOTE: this PR also contains configurations that generate the file in the review environment. …
=> ULK-131 | Generate sitemap on build

.env.example, .github/workflows/staging.yml, CHANGELOG.md, package.json, src/domain/app/App.tsx, src/domain/app/appWideNotification/AppWideNotification.tsx, src/domain/app/appWideNotification/__tests__/AppWideNotification.test.tsx, src/domain/app/appWideNotification/_appWideNotification.scss, src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/testinLibraryUtils.tsx, src/index.scss, yarn.lock
After this addition, notifications can be added on the site by using environment variables.
Notifications must be enabled explicitly.
Users can dismiss notifications, but their choice resets on session end.
[ULK-162](https://helsinkisolutionoffice.atlassian.net/browse/ULK-162)
I've added unit tests to cover basic requirements.
=> ULK-162 | As a user I want to be able to see site wide notifications

CHANGELOG.md, package.json
-   Ski track related additional information from new extra field
-   Notification that can be configured with environment
-   Update about dialog text
=> Release 1.4.0 (back to develop)

CHANGELOG.md, package-lock.json, package.json, src/domain/app/appWideNotification/AppWideNotification.tsx, yarn.lock
Notification language support for Microsoft Edge- and Safari-browsers.
Some browsers, like Edge and Safari, give also the country-code by default
as part of the browser language-setting ("en-US") when the page is opened first time.
Fix by always using the first two letters of the language.
Before fix:
After fix:
=> Fix App Wide Notification language

CHANGELOG.md, package-lock.json, package.json
-   Notification language support for Microsoft Edge- and Safari-browsers
=> Release 1.5.1

src/domain/unit/details/UnitDetails.tsx
Add null-check to otherinfo www-attribute.
Fixes: https://github.com/City-of-Helsinki/outdoors-sports-map/issues/168
=> Add null-check to otherinfo www-attribute

src/domain/map/MapView.tsx
Check if the event target is a path element.
Fixes: https://github.com/City-of-Helsinki/outdoors-sports-map/issues/169
=> Check if the event target is a path element

src/domain/unit/state/search/actions.ts
Fixes: https://github.com/City-of-Helsinki/outdoors-sports-map/issues/177
=> Use explicit type parameter in search suggestions

src/domain/unit/state/search/saga.ts, yarn.lock
Remove duplicate Digitransit addresses from search suggestions.
Fixes: https://github.com/City-of-Helsinki/outdoors-sports-map/issues/174
Now the `Petikko, Vantaa` is in search suggestions only once, not twice as earlier.
=> Remove duplicate Digitransit addresses from search suggestions

src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/unitConstants.ts
Add more information:
- adds more information to the details of unit information
[HULK-32](https://project.anders.fi/browse/HULK-32)
- Click to see the details of an outdoor sport and see if More Information exists on the details under Information section
- Click to see the details of an outdoor sport and see if More Information exists on the details under Information section
=> Add more information

azure-pipelines-release.yml, azure-pipelines-review.yml, azure-pipelines-test.yml
[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)
=> devops pipeline fix pipeline template names

README.md, azure-pipelines-review.yml, azure-pipelines-test.yml
Default branch is master
[DEVOPS-573](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-573)
[DEVOPS-573]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build: test and review pipelines trigger from master DEVOPS-573

src/domain/unit/browser/UnitBrowserAddressBar.tsx
Fix address location by swapping the latitude and longitude values to get the correct location.
=> Fix address location

public/index.html
Update Matomo-tracking to use the new DigiaIiris-service.
Refs HUL-20
=> Update Matomo-tracking to use DigiaIiris-service

src/common/_variables.scss, src/domain/map/MapGeometry.tsx, src/domain/map/MapUnit.tsx, src/domain/map/_mapGeometry.scss
Improve route selection:
- Select route also on map line geometry click
- Use dashed bolder blue colour to highlight route selection visually better
Refs HUL-22
=> Improve route selection

src/global.scss
Increase height profile close button icon size
=> Increase height profile close button icon size

src/global.scss
Increase height profile browse buttons sizes.
=> Increase height profile browse buttons sizes

src/domain/app/useAppSearch.ts, src/domain/unit/browser/resultList/__tests__/UnitBrowserResultList.test.tsx
Change unit sort default from distance to condition.
Refs HUL-30
=> Change unit  sort default to condition
