City-of-Helsinki/outdoors-sports-map

src/modules/unit/components/SingleUnitModalContainer.js, src/modules/unit/helpers.js
Reittiopas-link used to be generated in API, now it's created here.
Restore additional info link, `unit.url` has changed to `unit.www`.
=> KUVA-153: Add lost reittiopas and additional info links to place information

package.json, src/modules/map/constants.js, src/modules/unit/components/MapView.js, yarn.lock
Notes:
new tile pipeline might still be have some issues with caching. This cannot yet be used in production. Still, ulkoliikunta.fi is a good candidate for initial deployment.
Questions:
* this keeps the CRS definitions in the code and comments out the settings of the CRS. Is that appropriate? Or should the information retained in git history?
* If the CRS is kept in code, I'd like to have it defined in the same place as the tilesource, given that they are intricately linked. Good?
* Is there some way to pass the CRS prop to Map only if it is defined? Of course, a viable workaround would be to define a web mercator CRS, but that seems silly.
All these apply to all of our projects. Do we want to keep at least vestigial support for alternate projections, if we move to a web mercator based …
=> [WIP] Use web mercator tiles from the new helsinki tile pipeline

yarn.lock
The CI build and local builds would sometimes fails due to a bug in
some node versions which made them incompatible with some bable
dependencies we specified.
ref: https://github.com/babel/babel/issues/11216
=> Fix broken build

.gitignore, CHANGELOG.md, src/index.html, src/modules/common/components/translation/TranslationProvider.js, src/modules/common/components/translation/__tests__/TranslationProvider.test.js
The goal of this PR is to make sure that the language of the application matches with the HTML document. This is important for accessibility.
- I changed the default HTML document language into `fi` because that's the default language for the application
- I made sure that the HTML document language is synced with the application language on mount
- I made sure that whenever the application language is changed, so it the HTML document language
The solution should work for this purpose. It would fail if this application were server rendered.
[ULK-88](https://helsinkisolutionoffice.atlassian.net/browse/ULK-88)
[ULK-89](https://helsinkisolutionoffice.atlassian.net/browse/ULK-89)
I've modified the `TranslationProvider` test to take HTML document language into account.
1. Start the application …
=> ULK-88 | Sync HTML document language with app language

.github/workflows/test.yml, .gitlab-ci.yml, CHANGELOG.md
GitLab will be decommissioned soon and everything will be moved to GitHub. Therefore, run tests in GitHub as well.
=> Chore | Run tests in GitHub

CHANGELOG.md, src/modules/unit/components/LanguageChanger.js, src/modules/unit/components/MapView.js, src/modules/unit/components/__tests__/LanguageChanger.test.js
Adds lang attribute to language toggles so that their language content is correctly marked to differ from that of the page.
Also adds a `href` attribute so that the anchor become focusable.
[ULK-90](https://helsinkisolutionoffice.atlassian.net/browse/ULK-90)
I've added unit tests to the `LanguageChanger` component that checks that this attribute is applied.
By using a screen reader (for instance CMD+F5 on Mac)
1. Navigate to language controls in the manner you seem fit
2. Expect the content of language links ("Svenska", "English") to be read with the correct voice. In other words, Svenska is read as it would be by a Swedish speaker.
=> ULK-90 | Add lang attributes to language toggles

CHANGELOG.md, src/modules/unit/components/SingleUnitModalContainer.js
Adds a href attribute to the unit close anchor so that it's focusable with the keyboard. Prevents the default action to that it does not refresh the page.
[ULK-92](https://helsinkisolutionoffice.atlassian.net/browse/ULK-92)
This has been tested manually. I'll add unit tests in ULK-91.
1. Select an unit (for instance http://localhost:5000/unit/53989)
2. Use tab to navigate page
3. Expect to be able to focus the close button
4. Expect to be able to close the modal with the close button by only using your keyboard
=> ULK-92 | Make unit modal closable with keyboard

CHANGELOG.md, locales/en.json, locales/fi.json, locales/sv.json, src/modules/unit/components/SingleUnitModalContainer.js, src/modules/unit/components/__tests__/SingleUnitModalHeader.test.js
Adds an accessible name for unit modal close link by applying an aria-label to the close icon.
[ULK-91](https://helsinkisolutionoffice.atlassian.net/browse/ULK-91)
I've added unit level tests which check the behaviour of the close link.
1. Navigate to close button (for instance using tab)
2. Expect to hear a name for it (such as "Sulje", "Close" etc.)
=> ULK-91 | Add accessible name for unit modal close link

CHANGELOG.md, src/modules/map/components/Control.js, src/modules/map/components/_control.scss
Also fixes the locator button.
[ULK-108](https://helsinkisolutionoffice.atlassian.net/browse/ULK-108)
This has been tested manually. I've checked that the button is accessible by going through the page with <kbd>Shift</kbd> + <kbd>Tab</kbd> in reverse.
1. Go through the page in reverse (to avoid going through the map) with <kbd>Shift</kbd> + <kbd>Tab</kbd>
2. Expect to be able to focus info button
3. Expect to be able to open info menu
=> ULK-108 | Fix info button that's not reachable with keyboard

CHANGELOG.md, src/modules/unit/components/SingleUnitModalContainer.js, src/modules/unit/components/_single-unit-modal.scss, src/modules/unit/helpers.js
Current logic for rendering opening hours picks one opening hour to render. This PR changes the code so that all opening hours are rendered. Opening hours should be separated by a slight margin.
[ULK-109](https://helsinkisolutionoffice.atlassian.net/browse/ULK-109)
This has been tested manually.
1. Access unit `/unit/40493` (for instance https://outdoors-sports-map-feature-ul-53.newtest.kuva.hel.ninja/unit/40493)
2. Expect to see a long body of text.
3. Some things may be formatted oddly. That's OK.
=> ULK-109 | Show all opening hours

CHANGELOG.md, locales/en.json, locales/fi.json, locales/sv.json, src/index.scss, src/modules/common/components/OutboundLink.js, src/modules/common/components/__tests__/OutboundLink.test.js, src/modules/common/components/_outbound-link.scss, src/modules/home/components/Disclaimer.js, src/modules/unit/components/MapView.js, src/modules/unit/components/SingleUnitModalContainer.js
Refactors outbound links into its own component. The component implements a warning message that's visible while hovering, focusing or holding an element active. 
[ULK-95](https://helsinkisolutionoffice.atlassian.net/browse/ULK-95)
I've unit tested the new component and used a screen reader to ensure that the warning is read as expected.
1. Access Allas Seapool: `/unit/50401`
2. Browse through the links
3. Expect to hear "Open a new window" when accessing links that target a new window
4. Expect to see a black bordered white box with black text
=> ULK-95 | Warn when opening link in a new window

CHANGELOG.md, locales/en.json, locales/fi.json, locales/sv.json, src/index.scss, src/modules/common/_common.scss, src/modules/common/components/App.js, src/modules/common/components/JumpLink.js, src/modules/common/components/Page.js, src/modules/common/components/__tests__/JumpLink.test.js, src/modules/common/components/__tests__/Page.test.js, src/modules/common/components/_jump-link.scss, src/modules/common/components/_page.scss, src/modules/home/components/HomeContainer.js
Add a jump to content link to the beginning of the page.
It should be hidden by default, but become visible when focused. It should be the first focusable element on the page. The should move the user's focus to the main content, skipping any repeated content.
Note that currently there's no repeated content on this application so nothing is skipped.
[ULK-93](https://helsinkisolutionoffice.atlassian.net/browse/ULK-93)
I've added unit level tests which check the new JumpLink and Page components.
While using a screen reader
1. Expect to see no skip to content link by default
2. When tabbing into the page expect jump to content link to become visible
3. Expect link to move focus into main content
=> ULK-93 | Add jump link

CHANGELOG.md, locales/en.json, locales/fi.json, locales/sv.json, src/modules/unit/__tests__/UnitFilterLabel.test.js, src/modules/unit/__tests__/__snapshots__/UnitFilterLabel.test.js.snap, src/modules/unit/components/DropdownIndicator.js, src/modules/unit/components/UnitFilterButton.js, src/modules/unit/components/UnitFilterLabel.js, src/modules/unit/components/UnitFilterLabelButton.js, src/modules/unit/components/UnitFilters.js
Adds a more complete description to the sub menu toggle button and improves aria support.
Also marks visual icons, which contain duplicate information, as hidden on screen reading devices.
[ULK-98](https://helsinkisolutionoffice.atlassian.net/browse/ULK-98)
This has been tested manually with Safari and VoiceOver.
1. Access home page
2. Navigate to "choose sport" button
3. Expect to hear (for instance): "Skiing, Choose sport, collapsed, button"
4. Navigate to "choose condition" button
5. Expect to hear (for instance": "In all Conditions, Choose conditions, collapsed, button"
=> ULK-98 | Fix insufficient labels on sub menus

CHANGELOG.md, src/modules/common/enzymeHelpers.js, src/modules/unit/components/ListView.js, src/modules/unit/components/__tests__/ListView.test.js
Adds a href attribute to the show more link and cancel the default action. This makes the link focusable with the keyboard and screen reader.
[ULK-100](https://helsinkisolutionoffice.atlassian.net/browse/ULK-100)
I've added a unit test that checks the functionality of the link.
When using a screen reader
1. On the home page
2. Toggle on the list view
3. Browse to the load more link
4. Expect the link to be focusable
5. Expect clicking it to load more units
=> ULK-100 | Fix unreachable show more link

CHANGELOG.md, src/modules/common/components/Page.js, src/modules/common/components/__tests__/Page.test.js, src/modules/home/components/HomeContainer.js
Adds logic which generate unique titles for each based on unit names.
[ULK-112](https://helsinkisolutionoffice.atlassian.net/browse/ULK-112)
I've expanded the unit tests for the `<Page />` component.
1. Select an unit
2. Expect title to change to a unique string
3. Close the unit modal
4. Expect title to change back
=> ULK-112 | Add unique titles to pages

CHANGELOG.md, src/modules/common/_variables.scss, src/modules/unit/components/_single-unit-modal.scss
Changes the primary colour to one that has enough contrast.
[ULK-104](https://helsinkisolutionoffice.atlassian.net/browse/ULK-104)
I've manually checked the views and used chrome's tooling to check that the contrast ratio now fills AA standards.
I don't really know what's the best approach here for testing. If you have the tools, for instance VisBug, you can use it to check the contrast for the white text on blue background.
=> ULK-104 | Fix insufficient contrast in primary color

CHANGELOG.md, src/modules/unit/components/UnitBrowser.js, src/modules/unit/components/_unit-browser.scss
Adds an empty alt tag to the location icon to mark it as decorative. Changes the wrapping DIV into a button so that it's accessible with keyboard.
[ULK-106](https://helsinkisolutionoffice.atlassian.net/browse/ULK-106)
I've tested this change manually with Safari and VoiceOver
1. Navigate to current address element
2. Expect there to be no notice of a graphical element
3. Expect for the current address to be read
4. Expect for the element to be a button
=> ULK-106 | Fix current address not read by screen readers

src/modules/common/components/OutboundLink.js
Some screen readers do not read the title attribute so we must also use
aria-label to be accessible. The title attribute is still useful
because it allows for instance desktop users to see what the icon
means.
=> FIX | Add aria label to outbound links

CHANGELOG.md, src/modules/unit/components/UnitFilterLabelButton.js, src/modules/unit/components/UnitFilterOptionsWrapper.js, src/modules/unit/components/UnitFilters.js, src/modules/unit/components/_unit-filters.scss
The dropdown filters under the search bar did not have a proper connection between the control and the options.
This PR changes the DOM order so that the options appear after the control, and adds aria attributes that should be helpful.
I had to include a bit of a hack in the options list. It was hard to implement without using `position: absolute`, but this came with the caveat that the options would no longer push the content that followed them downwards. Instead the options would hide content underneath them. In order to avoid this I implemented a mechanism where there's a placeholder component that's relatively positioned which then moves the content downwards. I could not come up with a better approach although I am sure there are some. …
=> ULK-112 | Fix DOM order of units filter sub menu

CHANGELOG.md, src/modules/search/saga.js, src/modules/unit/helpers.js
Returning an empty result on an empty search was against accessibility guidelines.
This change aims to change the search procedure so that an empty search returns all units.
It was quite difficult to find the best approach to make this change even though it's relatively simple. I tried multiple approaches and deemed this to be the most simple one to implement.
[ULK-107](https://helsinkisolutionoffice.atlassian.net/browse/ULK-107)
I've tested this manually
1. Make a search
2. Expect to see correct results
3. Make an empty search
4. Expect to see all results
5. Make another search
6. Expect to see correct results
=> ULK-107 | Fix empty search returning nothing

CHANGELOG.md, src/modules/map/components/DropdownControl.js, src/modules/unit/components/MapView.js, src/modules/unit/components/_map-view.scss
Previously the info button was not usable with keyboard or screen readers. After this change it should be usable with both.
DOM order was changed so that the option list comes right after the info toggle button.
Missing aria definitions were added.
[ULK-111](https://helsinkisolutionoffice.atlassian.net/browse/ULK-111)
I've tested this manually.
1. Access the info button
2. Expect for it to have a name
3. Open it
4. Tab forward
5. Expect to land on the options
6. Expect each option to be focusable
7. Expect each option to have an accessible name that matches with the visual representation
8. Expect decorative icons to be hidden
The content that can be opened through the menu won't be accessible after this change.
=> ULK-111 | Improve service info button accessibility

CHANGELOG.md, src/modules/map/AriaHiddenIcon.js, src/modules/map/components/UserLocationMarker.js, src/modules/unit/components/UnitMarker.js
Adds aria-hidden definition to map markers.
This is against best practises because we are hiding focusable content. It'll still be accessible for screen reader users who use tab to navigate. This approach was advised in the accessibility report.
[ULK-96](https://helsinkisolutionoffice.atlassian.net/browse/ULK-97)
I've tested this manually with Safari and VoiceOver.
1. Tab through the search UI until you hit the map markers
2. Expect markers to be focused while hearing nothgin
1. Move through the UI using text navigation (<kbd>Ctrl</kbd> + <kbd>Opt</kbd> + <kbd>Right Arrow</kbd> / <kbd>Left Arrow</kbd>)
2. Expect markers to be ignored
=> ULK-96 | Hide map markers with aria-hidden

CHANGELOG.md, locales/en.json, locales/fi.json, locales/sv.json, src/modules/unit/components/SingleUnitModalContainer.js, src/modules/unit/components/_single-unit-modal.scss, src/modules/unit/helpers.js
Renames the directions sections into "links" section and adds a link to Palvelukartta into it.
[ULK-118](https://helsinkisolutionoffice.atlassian.net/browse/ULK-118)
I've tested this manually.
1. Access a unit
2. Expect to see links section
3. Expect it to contain a link into Palvelukartta
4. Expect the link to point to the same localisation of Palvelukartta as is selected in Ulkoliikuntakartta
=> ULK-118 | Add link to palvelukartta

CHANGELOG.md, src/modules/unit/components/MapView.js
Refactor `centerMapToUnit` method to move the new center location by 250px down. This is achieved with Leaflet's built-in functionality. 
When a unit is selected the map is always zoomed to the default zoom level. This is on mobile really annoying as one needs often to zoom in multiple levels to be able to select anything from the map. This makes the app hard to use on mobile.
Tested on local dev environment, with desktop and mobile.
Original PR #71 (@vaahtokarkki)
[ULK-119](https://helsinkisolutionoffice.atlassian.net/browse/ULK-119)
Spin up dev environment and click some units. On mobile, make sure that the unit is visible and not under the info box.
=> ULK-119 | Preserve the zoom level when an unit is selected

src/index.js, src/modules/common/components/App.js, src/modules/common/components/LanguageAwareRoutes.js, src/modules/common/components/Link.js, src/modules/common/components/ResetFocus.js, src/modules/common/components/Root.js, src/modules/common/constants.js, src/modules/common/helpers.js, src/modules/common/history.js, src/modules/common/hooks/useReactRouterNavigationSideEffect.js, src/modules/common/hooks/useScrollToTop.js, src/modules/common/i18n.js, src/modules/common/pathUtils.js, src/modules/common/routes.js, src/modules/home/components/HomeContainer.js, src/modules/home/components/Logo.js, src/modules/language/constants.js, src/modules/map/components/Map.js, src/modules/search/components/UnitSuggestion.js, src/modules/unit/components/LanguageChanger.js, src/modules/unit/components/ListView.js, src/modules/unit/components/SingleUnitContainer.js, src/modules/unit/components/UnitBrowser.js, src/modules/unit/components/__tests__/LanguageChanger.test.js, src/modules/unit/components/__tests__/SingeluUnitContainer.test.js, src/modules/unit/components/_unit-popup.scss
By including the language in the URL, we make it possible for the site to be indexed in multiple languages.
This PR uses an approach where the user is redirected from non-language-aware addresses to a language aware version. In order to avoid re-directs, the Link component automatically applies the current language to paths.
I also fixed some navigation related bugs in this PR:
* Search parameters were not retained when an unit was opened
* Focus did not reset on page change
* Scroll was not reset on page change
[ULK-134](https://helsinkisolutionoffice.atlassian.net/browse/ULK-134)
=> ULK-134 | Include language in the url

CHANGELOG.md, src/domain/app/appRoutes.ts, src/domain/home/HomeContainer.tsx, src/domain/map/Map.tsx, src/domain/map/MapUnit.tsx, src/domain/map/MapUnits.tsx, src/domain/map/MapView.tsx, src/domain/meta/LanguageMeta.tsx, src/domain/unit/browser/resultList/UnitBrowserResultList.tsx, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/details/useSyncUnitNameWithLanguage.ts
After this change, unit details pages will attempt to add the unit's name into the slug of the url.
* If the unit's name is not translated to the current language, the slug won't be amended
* The main purpose is to make the link more readable for users--insensible content in the slug may hamper this cognition
* The slug is updated when language is updated
* By default links point to slugs that have a unit name in them
* Meta tags have been amended to take the changed slug into account
[ULK-133](https://helsinkisolutionoffice.atlassian.net/browse/ULK-133)
=> ULK-133 | Add unit name in the slug of the unit details url

CHANGELOG.md, src/domain/map/MapView.tsx, src/domain/map/mapConstants.ts
Previously the basemap was always in Finnish.
After this change the basemap that corresponds to the application language is used. The Finnish and English basemaps seem to be mostly the same, but the Swedish version has a very different copy.
[ULK-141](https://helsinkisolutionoffice.atlassian.net/browse/ULK-141)
This change should fix this issue: https://github.com/City-of-Helsinki/outdoors-sports-map/issues/50
=> ULK-141 | Fix basemap always using Finnish terminology

src/domain/home/_home.scss, src/domain/map/Map.tsx, src/domain/unit/UnitView.tsx, src/domain/unit/browser/UnitBrowser.tsx, src/domain/unit/browser/_unitBrowser.scss, src/domain/unit/browser/resultList/UnitBrowserResultList.tsx, src/domain/unit/browser/resultList/_unitBrowserResultList.scss, src/domain/unit/details/useSyncUnitNameWithLanguage.ts
When the user completes a search, opens a unit and then closes the unit, they should be taken back to their original search.
Unexpected behaviour caused this stored search to be reset, which broke this functionality.
The `useSyncUnitNameWithLanguage` didn't properly pass on the current search state.
`useSyncUnitNameWithLanguage` was also unexpectedly fired, because the `history` package unexpectedly decoded paths before passing them on to the history API, causing "identical" urls to mismatch.
=> Fix location store reset

CHANGELOG.md, src/domain/app/AppFeedbackModal.tsx
The feedback form would always fail if the user did not provide their email.
=> Fix feedback form when user doesn't give email

src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/unitConstants.ts, src/domain/unit/unitHelpers.ts
Add control information under Info section in unit detail view. Information is shown only if unit data contains a connection with `#valvottu` tag.
Customer wanted this information to be visible. 
[HULK-2](https://helsinkisolutionoffice.atlassian.net/browse/HULK-2)
There is a new unit test and I also tested it with mocked API.
Because `#valvottu` tag data is not yet available in the backend, you have to mock the API using a tool like [Mockoon](https://mockoon.com/). Make sure all languages are working.
=> HULK-2: Show controlled information for beaches/swimming places

src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/unitConstants.ts, src/domain/unit/unitHelpers.ts
Add heating information under Info section in unit detail view. Information is shown only if unit data contains a connection with `#lämmitys` tag.
Be aware, that this PR is based on #140 so it is probably best to merge that first.
Customer wanted this information to be visible.
[HULK-4](https://helsinkisolutionoffice.atlassian.net/browse/HULK-4)
There is a new unit test and I also tested it with mocked API.
Because #lämmitys tag data is not yet available in the backend, you have to mock the API using a tool like [Mockoon](https://mockoon.com/). Make sure all languages are working.
=> HULK-4: Show heating information

src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/unitConstants.ts, src/domain/unit/unitHelpers.ts
Add lighting information under Info section in unit detail view. Information is shown only if unit data contains a connection with `#valaisu` tag.
Be aware, that this PR is based on #141 so it is probably best to merge that first.
Customer wanted this information to be visible.
[HULK-6](https://helsinkisolutionoffice.atlassian.net/browse/HULK-6)
There is a new unit test and I also tested it with mocked API.
Because `#valaisu` tag data is not yet available in the backend, you have to mock the API using a tool like [Mockoon](https://mockoon.com/). Make sure all languages are working.
=> HULK-6: Show lighting information

src/domain/home/HomeContainer.tsx, src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/details/_unitDetails.scss, src/domain/unit/unitConstants.ts, src/domain/unit/unitHelpers.ts
Change unit details view to be expandable on mobile devices.
`IsExpanded` state is stored on the parent controller so that user don't have to expand the view every time a new unit is selected. There is a simple animation when component is expanded or collapsed. Also, the icon is rotated 180 degrees to indicate the element's movement direction.
On smaller screen the details views hides most of the map which makes using the service a bit tricky. 
[HULK-8](https://helsinkisolutionoffice.atlassian.net/browse/HULK-8)
Manual testing. Unfortunately my frontend testing skills are not good enough to write unit tests for this kinds of features 🙈 
Open the UI with a mobile device or browser device emulator. Screen width have to be smaller than `768px`. Make sure expanding and collapsing works as …
=> HULK-8 - Expandable unit details on mobile devices

.env.example, src/domain/app/appWideNotification/AppWideNotification.tsx, src/domain/app/appWideNotification/__tests__/AppWideNotification.test.tsx, src/domain/app/appWideNotification/actions.ts, src/domain/app/appWideNotification/appWideNotificationConstants.ts, src/domain/app/appWideNotification/reducer.ts, src/domain/app/appWideNotification/saga.ts, src/domain/app/appWideNotification/selectors.ts, src/domain/bootstrap/createRootReducer.ts, src/domain/bootstrap/rootSaga.ts
This PR will add support for dynamic app wide notifications, that are fetched from servicemap api `/announcement`-endpoint with extra GET-parameter `outdoor_sports_map_usage=1`. Previously env-variables were used for this purpose, so this feature will add system admin a possibility to dynamically set up announcements to outdoor sports map application.
Browser SessionStorage is used to store announcement id and when user closes the notification dialog, notifications with the same id are not shown after page reload, unless the browser SessionStorage is cleared.
Refs HULK-3
Manual testing with servicemap test API: https://palvelukartta-api-test.agw.arodevtest.hel.fi/v2/announcement/ and locally, since this feature is not yet in the servicemap api production.
Testing can be currently done via …
=> Dynamic App wide notifications

src/domain/unit/state/search/actions.ts
Latest API-changes require explicit type-mapping in freetext-search, use it to overcome search-issues.
Freetext-search was not working, because some of the latest search-results in the new search engine do not have a separate `id`-field. This happens to for example addresses, where the object identity is generated by different means. Solve this issue by using a an explicit type `unit` in search, as we need to search only units.
Fixes: https://github.com/City-of-Helsinki/outdoors-sports-map/issues/175
Locally.
Can be tested locally.
=> Use explicit type parameter in freetext-search

CHANGELOG.md, package.json, yarn.lock
-   [#170](https://github.com/City-of-Helsinki/outdoors-sports-map/pull/170) Upgrade React to 17.x with related application packages and move to using Node 18 LTS
-   [#172](https://github.com/City-of-Helsinki/outdoors-sports-map/pull/172) Missing www value in connections causes the frontend to fail
-   [#173](https://github.com/City-of-Helsinki/outdoors-sports-map/pull/173) Application throws error to browsers console when ski map route is clicked
-   [#176](https://github.com/City-of-Helsinki/outdoors-sports-map/pull/176) Freetext-search gives JS-error occasionally
-   [#178](https://github.com/City-of-Helsinki/outdoors-sports-map/pull/178) Search suggestions give JS-error occasionally
-   [#179](https://github.com/City-of-Helsinki/outdoors-sports-map/pull/179) Duplicate keys in search …
=> Release 2.0.0

src/domain/unit/details/UnitDetails.tsx
React Markdown was updated, and the old values provided to `allowedElements` did not work anymore
Tested on the test API by providing notice data and verifying it works on the map
=> Fix missing notice text by updating allowedElements in ReactMarkdown

src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/state/reducer.ts, src/domain/unit/unitConstants.ts, src/domain/unit/unitHelpers.ts
Automatically change the latest primary observation to be either satisfactory or unknown. If a certain amount of days
has passed since the last observation, do the automatic change. Each sport has its own configuration for the number of days.
Current settings are:
* Swimming:
* 5 days or more --> unknown
* Skiing:
* 7 days or more --> satisfactory
* 10 days or more --> unknown
* Ice skating:
* 10 days or more --> unknown
=> Automatic satisfactory/unknown observation status

src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/details/_unitDetails.scss
Add water quality information:
- adds water quality information to the details of a swimming place whenever available
[HULK-22](https://project.anders.fi/browse/HULK-22)
Click to see the details of a swimming place check if water quality information is available and displayed (example swimming place with water quality info `Marjaniemi beach`)
Click to see the details of a swimming place check if water quality information is available and displayed (example swimming place with water quality info `Marjaniemi beach`)
Water quality Info:
=> Add water quality information to swimming places

src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/unitConstants.ts
Add parking and Other services Information:
- adds `Parking` information to outdoor sport details `Information` section when there exists `#pysäköinti `tag in the connections.
- adds `Other services` information to outdoor sport details `Information` section when there exists `#muut_palvelut` tag in the connections.
[HULK-21](https://project.anders.fi/browse/HULK-21) [HULK-19](https://project.anders.fi/browse/HULK-19)
- Click to see the details of an outdoor sport and see if `Parking` / `Other services` information exists on the details under `Information` section
- Click to see the details of an outdoor sport and see if `Parking` / `Other services` information exists on the details under `Information` section
=> Add parking information

src/domain/service/saga.ts, src/domain/service/serviceHelpers.ts, src/domain/unit/browser/UnitBrowser.tsx, src/domain/unit/state/actions.ts, src/domain/unit/state/search/actions.ts, src/domain/unit/unitConstants.ts, src/domain/unit/unitHelpers.ts
Display only season sports:
- displays only on season sports as options for Choosing sport
- Search suggestions should only contains on season sports
- initial request to load data should only contains on season service ids
[HULK-29](https://project.anders.fi/browse/HULK-29)
See if only season sports are displayed as option for choosing sport  `Summer : Swimming  /  Winter : Skiing, Skating, Ice swimming`
See if only season sports are displayed as option for choosing sport  `Summer : Swimming  /  Winter : Skiing, Skating, Ice swimming`
Season sport options:
Season search suggestions:
Season request service ids(loading data):
=> Display only season sports

src/domain/home/HomeContainer.tsx, src/domain/map/mapConstants.ts
Zoom in to selected Unit:
- when a search suggestion is selected, it zooms in to the selected unit.
- when a unit on the map is clicked, it should show the selected unit zoomed in.
[HULK-2](https://andersinno.atlassian.net/browse/HULK-2)
- search for a unit
- click on selected unit
- expect to see that selected unit zoomed in the map
- search for a unit
- click on selected unit
- expect to see that selected unit zoomed in the map
=> Zoom to unit when it is selected

src/domain/service/serviceConstants.ts, src/domain/unit/unitConstants.ts
Remove information points for now.
Some information points (that originate from LIPAS-source system) are not suitable for this service, thus we will not include any information point for now (until there is some other way to get correct units from the source).
[HUL-7](https://andersinno.atlassian.net/browse/HUL-7)
Locally.
=> Remove information points for now

public/index.html, src/domain/app/App.tsx, src/domain/app/CookieConsent.tsx, src/global.scss
Add Helsinki Design System CookieConsent modal to the page.
Refs [HUL-12](https://andersinno.atlassian.net/browse/HUL-12)
Tested in local development environment.
Example of the whole modal:
Also support for English and Swedish:
=> Add HDS CookieConsent modal

src/domain/app/CookieConsent.tsx
The language change worked only if the whole site language was changed. Fix it so that the language change works also when changed from the cookie modal.
=> Fix CookieConsent language change

src/domain/app/CookieConsent.tsx, src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json
Add details about Matomo to cookie consent modal.
=> Add Matomo cookie details

src/domain/app/AppHeader.tsx, src/domain/home/HomeContainer.tsx, src/domain/home/_home.scss
Add possibility to hide/show home-container.
Works in both, mobile and desktop layouts through new home-container header IconAngleDown-button.
Refs HUL-23
Home-container hidden:
Home-container shown:
=> Add possibility to hide/show home-container

src/domain/home/HomeContainer.tsx, src/domain/map/mapConstants.ts, src/domain/unit/browser/UnitBrowserAddressBar.tsx
Update map zooming:
- Increase detail zoom in level to 15. This will remove previous map jumps to different place.
- Decrease min zoom to level 10. This will allow user to zoom farther away
to see more at once with smaller screens.
Refs HUL-16
Previously selecting `Hakunila-Bisajärvi hiihtolatu 4,5km` zoomed map to Estonia coastline.
Now the map stays in Finland and zooms to correct unit.
=> Update map zooming

src/domain/app/useAppSearch.ts, src/domain/i18n/locales/en.json, src/domain/i18n/locales/fi.json, src/domain/i18n/locales/sv.json, src/domain/unit/browser/resultList/UnitBrowserResultList.tsx, src/domain/unit/browser/resultList/__tests__/UnitBrowserResultList.test.tsx, src/domain/unit/browser/resultList/useUnitSearchResults.ts, src/domain/unit/details/UnitDetails.tsx, src/domain/unit/details/__tests__/UnitDetails.test.tsx, src/domain/unit/details/_unitDetails.scss, src/domain/unit/unitConstants.ts, src/domain/unit/unitHelpers.ts
Add a new feature to save units as favorites. Favorites are stored in local storage. User can add or remove units from favorites in the unit details view. Favorites are displayed in the unit search results view when the favorites filter is selected. If user has favorites in the selected sport, the list is sorted by favorites by default.
Refs HUL-28
Feature has been tested locally and also by some unit tests.
Adding a favorite:
Removing a favorite:
Favorites filter:
=> Save units as favorites

src/domain/app/CookieConsent.tsx
Ensure `currentLanguage` is either 'fi', 'sv', or 'en' in the CookieConsent component and default to 'en' if not. This fixes issue where the page was white/blank on the first load due to incorrect language type.
Refs HUL-29
=> Validate currentLanguage in CookieConsent
